### ISSUE TITLE
Make an Android app

### ISSUE THREAD

**Issue by Globidev** [best-coloc-ever/twitch-cast#15]
Having an Android app would be nice!
For backend resources, see [this page](https://github.com/best-coloc-ever/twitch-cast/wiki/Streaming-API)
For General documentation on Chromecast sender applications for Android, see [this page](https://developers.google.com/cast/docs/android_sender)

**Comment by Globidev** [comment]
@amanent
@valgrin is not doing his job very well :'(

**Comment by amanent** [comment]
A Google Cast SDK update was announced @I/O. Should be coming in June

**Comment by Globidev** [comment]
Chrome on Android now supports native casting through the web API.
No more need for a native app :tada:
