### ISSUE TITLE
Make things prettier

### ISSUE THREAD

**Issue by Globidev** [best-coloc-ever/twitch-cast#6]
@amanent 

[This view needs some tweaks](https://github.com/best-coloc-ever/twitch-cast/blob/master/frontend%2Fchromecast%2Fsender.html)

**Comment by Globidev** [comment]
### Useful information

This is not yet documented but listed below are the current endpoints
Some route names are bad and POST requests work with form data which is kind of dumb. This will change soon

#### Streaming API
###### [Proxy pass location: /streamer](https://github.com/best-coloc-ever/twitch-cast/blob/master/frontend%2Fnginx.conf#L25-L28)
 - [`GET /streams`](https://github.com/best-coloc-ever/twitch-cast/blob/master/streamer%2Fapi.py#L20-L29)
List of currently monitored streams
Exemple reponse:

  ```json
  {
    "streams": [
      {
        "port": 50621, 
        "quality": "best", 
        "url": "twitch.tv/dotamajor"
      }, 
      {
        "port": 55488, 
        "quality": "low", 
        "url": "twitch.tv/streamerhouse"
      }
    ]
  }
```
 - [`POST /start?channel=name&quality=key`](https://github.com/best-coloc-ever/twitch-cast/blob/master/streamer%2Fapi.py#L31-L54)
Send a monitoring request
Example response:

  ```json
  {
    "status": "OK" 
  }
```
status can be one of:

  ```json
  ["OK", "ALREADY_STARTED", "UNAVAILABLE"]
```

#### HLS API
###### [Proxy pass location: /hls-proxy](https://github.com/best-coloc-ever/twitch-cast/blob/master/frontend%2Fnginx.conf#L30-L33)
- [`GET /proxies`](https://github.com/best-coloc-ever/twitch-cast/blob/master/hls-proxy%2Fapi.py#L21-L30)
List of currently active proxies
Example response:

  ```json
  {
    "proxies": [
      {
        "port": "50621", 
        "ready": true
      }, 
      {
        "port": "55488", 
        "ready": false
      }
    ]
  }
```
`ready` is set to `true` if the hls index file is present 
- [`POST /watch?port=num`](https://github.com/best-coloc-ever/twitch-cast/blob/master/hls-proxy%2Fapi.py#L32-L48)
Send a request to start proxying
Example response:

  ```json
  {
    "status": "OK" 
  }
```
status can be one of:

  ```json
  ["OK", "ALREADY_WATCHING"]
```

- [`POST /unwatch?port=num`](https://github.com/best-coloc-ever/twitch-cast/blob/master/hls-proxy%2Fapi.py#L50-L63)
Send a request to stop a proxy
Example response:

  ```json
  {
    "status": "OK" 
  }
```
status can be one of:

  ```json
  ["OK", "NOT_FOUND"]
```

**Comment by Globidev** [comment]
updated last comment because of #12

**Comment by amanent** [comment]
I don't know what is intended regarding the renaming of the routes, but you should consider having only the plural forms in the URL.
`GET /streams`
`GET /streams/{id}`
`POST /streams`
`DELETE /streams/{id}`

**Comment by Globidev** [comment]
Seems indeed like the common way to do it

**Comment by amanent** [comment]
Enjoy your party you fucking nerd

**Comment by Globidev** [comment]
updated API doc after #13

**Comment by Globidev** [comment]
The Streaming API is now documented [here](https://github.com/best-coloc-ever/twitch-cast/wiki/Streaming-API)
